apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: jhnginx
        image: 211.183.3.115/project/project:jh  # Docker 이미지 주소
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: harbor-registry 

---
- name: Deploy to Kubernetes
  hosts: localhost  # localhost 또는 실행할 호스트 지정
  become: true
  tasks:
    - name: Copy the YAML file to the master
      copy:
        src: deployment.yml
        dest: /home/user1/project_jenkis/deployment.yml
        owner: user1
        group: user1
        mode: '0664'
        
    - name: Deploy application using kubectl
      shell: sudo kubectl apply -f /home/user1/project_jenkis/deployment.yml

---

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
