- name: Deploy Kubernetes resources for project1
  hosts: localhost
  gather_facts: no
  become: true  # 권한 상승을 위해 추가
  environment:
    KUBECONFIG: "/home/jenkins/.kube/config"  # 환경변수로 KUBECONFIG 설정

  tasks:
    - name: Create Namespace for project1
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: project1

    - name: Create nginx Deployment for project1
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deploy
            namespace: project1
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: web
            template:
              metadata:
                labels:
                  app: web
              spec:
                imagePullSecrets:
                  - name: secret-harbor  # Harbor 레지스트리 비밀번호를 포함한 시크릿 사용
                containers:
                  - name: nginx
                    image: 211.183.3.115/project1/nginx:jh  # Docker 이미
