- name: Playbook 과 Jenkins를 이용한 CICD
  hosts: master  # Ansible에서 'master' 호스트를 설정해야 합니다.
  become: true  # root 권한으로 작업을 수행
  tasks:
  
    - name: Master에게 yml file 복사
      copy:
        src: deployment.yml  # 로컬에서 'deployment.yml' 파일을 복사
        dest: /home/user1/project_jenkis/deployment.yml  # 원격 서버의 경로
        owner: user1
        group: user1
        mode: '0664'  # 파일 권한 설정

    - name: deployment 배포
  shell: sudo kubectl apply -f /home/user1/project_jenkis/deployment.yml  # 배포 파일 경로 확인