- name: Deploy Kubernetes resources for project1
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Namespace for project1
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: project1

    - name: Create nginx Deployment for project1
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deploy
            namespace: project1
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: web
            template:
              metadata:
                labels:
                  app: web
              spec:
                imagePullSecrets:
                  - name: secret-harbor
                containers:
                  - name: nginx
                    image: 211.183.3.115/project1/nginx:jh
                    ports:
                      - containerPort: 80

    - name: Create Service for nginx Deployment
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: web-svc
            namespace: project1
          spec:
            selector:
              app: web
            ports:
              - port: 80
                targetPort: 80
            type: NodePort  # NodePort or LoadBalancer
