- name: Deploy Kubernetes resources for project1
  hosts: master
  gather_facts: no
  become: true
  environment:
    KUBECONFIG: "/home/jenkins/.kube/config"  # 환경변수로 KUBECONFIG 설정

  tasks:
    - name: Create nginx Deployment for project1
      k8s:
        state: present
        verify_ssl: no  # SSL 인증서 검증 비활성화
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deploy
            namespace: default  # 네임스페이스 없이 기본(default) 네임스페이스에 배포
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: web
            template:
              metadata:
                labels:
                  app: web
              spec:
                imagePullSecrets:
                  - name: secret-harbor
                containers:
                  - name: nginx
                    image: 211.183.3.115/project1/nginx:jh
                    ports:
                      - containerPort: 80

    - name: Create Service for nginx Deployment
      k8s:
        state: present
        verify_ssl: no  # SSL 인증서 검증 비활성화
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: web-svc
            namespace: default  # 네임스페이스 없이 기본(default) 네임스페이스에 서비스 생성
          spec:
            selector:
              app: web
            ports:
              - port: 80
                targetPort: 80
            type: NodePort
