- name: Deploy Kubernetes resources for project1
  hosts: k8s_nodes
  gather_facts: no
  become: true
  environment:
    KUBECONFIG: "/home/jenkins/.kube/config"
  tasks:
    - name: Create nginx Deployment for project1
      k8s:
        state: present
        verify_ssl: no
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deploy
            namespace: default
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: web
            template:
              metadata:
                labels:
                  app: web
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
